// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VendorListEntry = { name: string, path: string, digest: string, size_bytes: bigint, orphan: boolean, };
