// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VendorCheckEntry = { name: string, path: string, source_kind: string | null, source_ref: string | null, expected_digest: string | null, actual_digest: string | null, orphan: boolean, missing_vendor: boolean, missing_source: boolean, };
