// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VendorListEntry } from "./VendorListEntry";

export type VendorListOutput = { entries: Array<VendorListEntry>, };
