// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VendorCheckEntry } from "./VendorCheckEntry";

export type VendorCheckOutput = { drift: boolean, entries: Array<VendorCheckEntry>, orphaned: Array<string>, missing: Array<string>, };
